// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dms/v1/dms.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	stubs "github.com/oswee/stubs"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateDeliveryOrderRequest struct {
	DeliveryOrder        *DeliveryOrder `protobuf:"bytes,1,opt,name=delivery_order,json=deliveryOrder,proto3" json:"delivery_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateDeliveryOrderRequest) Reset()         { *m = CreateDeliveryOrderRequest{} }
func (m *CreateDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeliveryOrderRequest) ProtoMessage()    {}
func (*CreateDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91763f6e7a58dbd9, []int{0}
}

func (m *CreateDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *CreateDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeliveryOrderRequest.Merge(m, src)
}
func (m *CreateDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeliveryOrderRequest.Size(m)
}
func (m *CreateDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeliveryOrderRequest proto.InternalMessageInfo

func (m *CreateDeliveryOrderRequest) GetDeliveryOrder() *DeliveryOrder {
	if m != nil {
		return m.DeliveryOrder
	}
	return nil
}

type ListDeliveryOrdersRequest struct {
	StakeholderId        int64    `protobuf:"varint,1,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDeliveryOrdersRequest) Reset()         { *m = ListDeliveryOrdersRequest{} }
func (m *ListDeliveryOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryOrdersRequest) ProtoMessage()    {}
func (*ListDeliveryOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91763f6e7a58dbd9, []int{1}
}

func (m *ListDeliveryOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Unmarshal(m, b)
}
func (m *ListDeliveryOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Marshal(b, m, deterministic)
}
func (m *ListDeliveryOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryOrdersRequest.Merge(m, src)
}
func (m *ListDeliveryOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Size(m)
}
func (m *ListDeliveryOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryOrdersRequest proto.InternalMessageInfo

func (m *ListDeliveryOrdersRequest) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *ListDeliveryOrdersRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *ListDeliveryOrdersRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type ListDeliveryOrdersResponse struct {
	DeliveryOrders       []*DeliveryOrder `protobuf:"bytes,1,rep,name=delivery_orders,json=deliveryOrders,proto3" json:"delivery_orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListDeliveryOrdersResponse) Reset()         { *m = ListDeliveryOrdersResponse{} }
func (m *ListDeliveryOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryOrdersResponse) ProtoMessage()    {}
func (*ListDeliveryOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91763f6e7a58dbd9, []int{2}
}

func (m *ListDeliveryOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Unmarshal(m, b)
}
func (m *ListDeliveryOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Marshal(b, m, deterministic)
}
func (m *ListDeliveryOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryOrdersResponse.Merge(m, src)
}
func (m *ListDeliveryOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Size(m)
}
func (m *ListDeliveryOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryOrdersResponse proto.InternalMessageInfo

func (m *ListDeliveryOrdersResponse) GetDeliveryOrders() []*DeliveryOrder {
	if m != nil {
		return m.DeliveryOrders
	}
	return nil
}

type UpdateDeliveryOrderRequest struct {
	DeliveryOrder        *DeliveryOrder `protobuf:"bytes,1,opt,name=delivery_order,json=deliveryOrder,proto3" json:"delivery_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateDeliveryOrderRequest) Reset()         { *m = UpdateDeliveryOrderRequest{} }
func (m *UpdateDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeliveryOrderRequest) ProtoMessage()    {}
func (*UpdateDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91763f6e7a58dbd9, []int{3}
}

func (m *UpdateDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *UpdateDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeliveryOrderRequest.Merge(m, src)
}
func (m *UpdateDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeliveryOrderRequest.Size(m)
}
func (m *UpdateDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeliveryOrderRequest proto.InternalMessageInfo

func (m *UpdateDeliveryOrderRequest) GetDeliveryOrder() *DeliveryOrder {
	if m != nil {
		return m.DeliveryOrder
	}
	return nil
}

type DeleteDeliveryOrderRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeliveryOrderRequest) Reset()         { *m = DeleteDeliveryOrderRequest{} }
func (m *DeleteDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeliveryOrderRequest) ProtoMessage()    {}
func (*DeleteDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91763f6e7a58dbd9, []int{4}
}

func (m *DeleteDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *DeleteDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeliveryOrderRequest.Merge(m, src)
}
func (m *DeleteDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeliveryOrderRequest.Size(m)
}
func (m *DeleteDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeliveryOrderRequest proto.InternalMessageInfo

func (m *DeleteDeliveryOrderRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GeoCodeDeliveryOrderRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StakeholderId        int64    `protobuf:"varint,2,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoCodeDeliveryOrderRequest) Reset()         { *m = GeoCodeDeliveryOrderRequest{} }
func (m *GeoCodeDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GeoCodeDeliveryOrderRequest) ProtoMessage()    {}
func (*GeoCodeDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91763f6e7a58dbd9, []int{5}
}

func (m *GeoCodeDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoCodeDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *GeoCodeDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoCodeDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (m *GeoCodeDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoCodeDeliveryOrderRequest.Merge(m, src)
}
func (m *GeoCodeDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GeoCodeDeliveryOrderRequest.Size(m)
}
func (m *GeoCodeDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoCodeDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeoCodeDeliveryOrderRequest proto.InternalMessageInfo

func (m *GeoCodeDeliveryOrderRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GeoCodeDeliveryOrderRequest) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *GeoCodeDeliveryOrderRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeliveryOrder struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StakeholderId        int64    `protobuf:"varint,2,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	Reference            string   `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	DestinationAddress   string   `protobuf:"bytes,4,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	DestinationZip       string   `protobuf:"bytes,5,opt,name=destination_zip,json=destinationZip,proto3" json:"destination_zip,omitempty"`
	DestinationLat       float64  `protobuf:"fixed64,6,opt,name=destination_lat,json=destinationLat,proto3" json:"destination_lat,omitempty"`
	DestinationLng       float64  `protobuf:"fixed64,7,opt,name=destination_lng,json=destinationLng,proto3" json:"destination_lng,omitempty"`
	TotalWeight          float64  `protobuf:"fixed64,8,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	RoutingSequence      int64    `protobuf:"varint,9,opt,name=routing_sequence,json=routingSequence,proto3" json:"routing_sequence,omitempty"`
	Uuid                 string   `protobuf:"bytes,10,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveryOrder) Reset()         { *m = DeliveryOrder{} }
func (m *DeliveryOrder) String() string { return proto.CompactTextString(m) }
func (*DeliveryOrder) ProtoMessage()    {}
func (*DeliveryOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_91763f6e7a58dbd9, []int{6}
}

func (m *DeliveryOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryOrder.Unmarshal(m, b)
}
func (m *DeliveryOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryOrder.Marshal(b, m, deterministic)
}
func (m *DeliveryOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryOrder.Merge(m, src)
}
func (m *DeliveryOrder) XXX_Size() int {
	return xxx_messageInfo_DeliveryOrder.Size(m)
}
func (m *DeliveryOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryOrder proto.InternalMessageInfo

func (m *DeliveryOrder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeliveryOrder) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *DeliveryOrder) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationZip() string {
	if m != nil {
		return m.DestinationZip
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationLat() float64 {
	if m != nil {
		return m.DestinationLat
	}
	return 0
}

func (m *DeliveryOrder) GetDestinationLng() float64 {
	if m != nil {
		return m.DestinationLng
	}
	return 0
}

func (m *DeliveryOrder) GetTotalWeight() float64 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

func (m *DeliveryOrder) GetRoutingSequence() int64 {
	if m != nil {
		return m.RoutingSequence
	}
	return 0
}

func (m *DeliveryOrder) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateDeliveryOrderRequest)(nil), "oswee.dms.v1.CreateDeliveryOrderRequest")
	proto.RegisterType((*ListDeliveryOrdersRequest)(nil), "oswee.dms.v1.ListDeliveryOrdersRequest")
	proto.RegisterType((*ListDeliveryOrdersResponse)(nil), "oswee.dms.v1.ListDeliveryOrdersResponse")
	proto.RegisterType((*UpdateDeliveryOrderRequest)(nil), "oswee.dms.v1.UpdateDeliveryOrderRequest")
	proto.RegisterType((*DeleteDeliveryOrderRequest)(nil), "oswee.dms.v1.DeleteDeliveryOrderRequest")
	proto.RegisterType((*GeoCodeDeliveryOrderRequest)(nil), "oswee.dms.v1.GeoCodeDeliveryOrderRequest")
	proto.RegisterType((*DeliveryOrder)(nil), "oswee.dms.v1.DeliveryOrder")
}

func init() { proto.RegisterFile("dms/v1/dms.proto", fileDescriptor_91763f6e7a58dbd9) }

var fileDescriptor_91763f6e7a58dbd9 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x6d, 0x6f, 0xd2, 0x50,
	0x14, 0x4e, 0x61, 0x2f, 0x72, 0x18, 0x65, 0xb9, 0x68, 0xd2, 0x75, 0x9a, 0x21, 0x89, 0x8e, 0x25,
	0x86, 0x66, 0xf8, 0x0b, 0xdc, 0x30, 0xc6, 0x64, 0xd1, 0xc9, 0xa2, 0x26, 0x8b, 0xb1, 0xb6, 0xdc,
	0xb3, 0x72, 0x63, 0xe9, 0xad, 0xf7, 0xde, 0xb2, 0xe0, 0x67, 0xfd, 0xe4, 0xbf, 0xf5, 0x17, 0x98,
	0x5e, 0x60, 0xa3, 0xd0, 0x32, 0x63, 0xe2, 0x37, 0xfa, 0x9c, 0xe7, 0x3e, 0xe7, 0xfd, 0x00, 0xbb,
	0x74, 0x24, 0x9d, 0xf1, 0xb1, 0x43, 0x47, 0xb2, 0x13, 0x0b, 0xae, 0x38, 0xd9, 0xe1, 0xf2, 0x1a,
	0xb1, 0x93, 0x02, 0xe3, 0x63, 0xdb, 0xd4, 0xa0, 0x9f, 0x5c, 0x4d, 0xad, 0xad, 0x2f, 0x60, 0x9f,
	0x0a, 0xf4, 0x14, 0xf6, 0x30, 0x64, 0x63, 0x14, 0x93, 0xb7, 0x82, 0xa2, 0xe8, 0xe3, 0xb7, 0x04,
	0xa5, 0x22, 0x27, 0x60, 0xd2, 0x19, 0xee, 0xf2, 0xd4, 0x60, 0x19, 0x4d, 0xa3, 0x5d, 0xed, 0xee,
	0x77, 0x16, 0x45, 0x3b, 0xd9, 0xb7, 0x35, 0xba, 0xf8, 0xd9, 0xfa, 0x65, 0xc0, 0xde, 0x19, 0x93,
	0x2a, 0x43, 0x92, 0x73, 0x0f, 0x4f, 0xc0, 0x94, 0xca, 0xfb, 0x8a, 0x43, 0x1e, 0x52, 0x14, 0x2e,
	0xa3, 0xda, 0x43, 0xb9, 0x5f, 0x5b, 0x40, 0x5f, 0x53, 0x72, 0x00, 0xd5, 0xd8, 0x0b, 0xd0, 0x8d,
	0x92, 0x91, 0x8f, 0xc2, 0x2a, 0x35, 0x8d, 0xf6, 0x66, 0x1f, 0x52, 0xe8, 0x8d, 0x46, 0xc8, 0x53,
	0xa8, 0x0b, 0x94, 0x49, 0xa8, 0xdc, 0x18, 0x85, 0x9b, 0x1a, 0xac, 0xb2, 0x26, 0xd5, 0xa6, 0xf0,
	0x39, 0x8a, 0x73, 0x2f, 0xc0, 0x96, 0x0f, 0x76, 0x5e, 0x30, 0x32, 0xe6, 0x91, 0x44, 0xd2, 0x83,
	0x7a, 0x36, 0x5f, 0x69, 0x19, 0xcd, 0xf2, 0x5d, 0x09, 0x9b, 0x99, 0x84, 0x65, 0x5a, 0xd3, 0xf7,
	0x31, 0xfd, 0x9f, 0x35, 0x7d, 0x06, 0x76, 0x0f, 0x43, 0x2c, 0xf0, 0x60, 0x42, 0xe9, 0xa6, 0x8e,
	0x25, 0x46, 0x5b, 0x11, 0xec, 0xbf, 0x42, 0x7e, 0xca, 0xe9, 0x5f, 0xd1, 0x73, 0x5a, 0x52, 0xca,
	0x6b, 0x89, 0x05, 0xdb, 0x1e, 0xa5, 0x02, 0xa5, 0xd4, 0x95, 0xae, 0xf4, 0xe7, 0x9f, 0xad, 0xdf,
	0x25, 0xa8, 0x65, 0x3c, 0xfd, 0xab, 0x8b, 0x87, 0x50, 0x11, 0x78, 0x85, 0x02, 0xa3, 0x01, 0xce,
	0x9c, 0xdc, 0x02, 0xc4, 0x81, 0x06, 0x45, 0xa9, 0x58, 0xe4, 0x29, 0xc6, 0x23, 0x77, 0x1e, 0xcc,
	0x86, 0xe6, 0x91, 0x05, 0xd3, 0x8b, 0xa9, 0x85, 0x1c, 0xa6, 0xdd, 0xbd, 0x7d, 0xf0, 0x9d, 0xc5,
	0xd6, 0xa6, 0x26, 0x9b, 0x0b, 0xf0, 0x25, 0x8b, 0x97, 0x89, 0xa1, 0xa7, 0xac, 0xad, 0xa6, 0xd1,
	0x36, 0x32, 0xc4, 0x33, 0x4f, 0xad, 0x10, 0xa3, 0xc0, 0xda, 0x5e, 0x25, 0x46, 0x01, 0x79, 0x0c,
	0x3b, 0x8a, 0x2b, 0x2f, 0x74, 0xaf, 0x91, 0x05, 0x43, 0x65, 0xdd, 0xd3, 0xac, 0xaa, 0xc6, 0x3e,
	0x6a, 0x88, 0x1c, 0xc1, 0xae, 0xe0, 0x89, 0x62, 0x51, 0xe0, 0xca, 0xb4, 0x33, 0x69, 0xce, 0x15,
	0x5d, 0x95, 0xfa, 0x0c, 0xbf, 0x98, 0xc1, 0x84, 0xc0, 0x46, 0x92, 0x30, 0x6a, 0x81, 0x8e, 0x5e,
	0xff, 0xee, 0xfe, 0x2c, 0x43, 0xfd, 0x62, 0xc8, 0xe2, 0x58, 0x13, 0xc5, 0x98, 0x0d, 0x90, 0x7c,
	0x82, 0x46, 0xce, 0x72, 0x93, 0x76, 0x76, 0xd2, 0x8a, 0xf7, 0xdf, 0x5e, 0x37, 0x93, 0xa9, 0x7a,
	0xce, 0x98, 0x2f, 0xab, 0x17, 0x6f, 0xc2, 0x7a, 0xf5, 0x0f, 0xd0, 0xc8, 0x19, 0xf1, 0x65, 0xf5,
	0xe2, 0x2d, 0xb0, 0x1f, 0xcc, 0x98, 0x37, 0x07, 0xef, 0xe5, 0x28, 0x56, 0x13, 0xf2, 0x19, 0xee,
	0xe7, 0x2d, 0x03, 0x39, 0xca, 0x0a, 0xaf, 0x59, 0x98, 0xb5, 0x71, 0x77, 0x7f, 0x18, 0xb0, 0x97,
	0x41, 0xde, 0x25, 0x28, 0x26, 0xf3, 0x8e, 0x04, 0x40, 0x56, 0xcf, 0x0f, 0x39, 0xcc, 0x0a, 0x16,
	0x5e, 0x4b, 0xbb, 0x7d, 0x37, 0x71, 0x7a, 0xc9, 0x4e, 0x0e, 0x2e, 0x1f, 0x05, 0x4c, 0x0d, 0x13,
	0xbf, 0x33, 0xe0, 0x23, 0x47, 0xbf, 0x72, 0xa4, 0x4a, 0x7c, 0xe9, 0x4c, 0xff, 0x20, 0xfc, 0x2d,
	0x5d, 0x97, 0xe7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xad, 0xf9, 0x48, 0x31, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShippingServiceClient interface {
	CreateDeliveryOrder(ctx context.Context, in *CreateDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error)
	UpdateDeliveryOrder(ctx context.Context, in *UpdateDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error)
	DeleteDeliveryOrder(ctx context.Context, in *DeleteDeliveryOrderRequest, opts ...grpc.CallOption) (*stubs.Empty, error)
	GeoCodeDeliveryOrder(ctx context.Context, in *GeoCodeDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CreateDeliveryOrder(ctx context.Context, in *CreateDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error) {
	out := new(DeliveryOrder)
	err := c.cc.Invoke(ctx, "/oswee.dms.v1.ShippingService/CreateDeliveryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) UpdateDeliveryOrder(ctx context.Context, in *UpdateDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error) {
	out := new(DeliveryOrder)
	err := c.cc.Invoke(ctx, "/oswee.dms.v1.ShippingService/UpdateDeliveryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) DeleteDeliveryOrder(ctx context.Context, in *DeleteDeliveryOrderRequest, opts ...grpc.CallOption) (*stubs.Empty, error) {
	out := new(stubs.Empty)
	err := c.cc.Invoke(ctx, "/oswee.dms.v1.ShippingService/DeleteDeliveryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) GeoCodeDeliveryOrder(ctx context.Context, in *GeoCodeDeliveryOrderRequest, opts ...grpc.CallOption) (*DeliveryOrder, error) {
	out := new(DeliveryOrder)
	err := c.cc.Invoke(ctx, "/oswee.dms.v1.ShippingService/GeoCodeDeliveryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
type ShippingServiceServer interface {
	CreateDeliveryOrder(context.Context, *CreateDeliveryOrderRequest) (*DeliveryOrder, error)
	UpdateDeliveryOrder(context.Context, *UpdateDeliveryOrderRequest) (*DeliveryOrder, error)
	DeleteDeliveryOrder(context.Context, *DeleteDeliveryOrderRequest) (*stubs.Empty, error)
	GeoCodeDeliveryOrder(context.Context, *GeoCodeDeliveryOrderRequest) (*DeliveryOrder, error)
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_CreateDeliveryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CreateDeliveryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.dms.v1.ShippingService/CreateDeliveryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CreateDeliveryOrder(ctx, req.(*CreateDeliveryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_UpdateDeliveryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).UpdateDeliveryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.dms.v1.ShippingService/UpdateDeliveryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).UpdateDeliveryOrder(ctx, req.(*UpdateDeliveryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_DeleteDeliveryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeliveryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).DeleteDeliveryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.dms.v1.ShippingService/DeleteDeliveryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).DeleteDeliveryOrder(ctx, req.(*DeleteDeliveryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_GeoCodeDeliveryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoCodeDeliveryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).GeoCodeDeliveryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.dms.v1.ShippingService/GeoCodeDeliveryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).GeoCodeDeliveryOrder(ctx, req.(*GeoCodeDeliveryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.dms.v1.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeliveryOrder",
			Handler:    _ShippingService_CreateDeliveryOrder_Handler,
		},
		{
			MethodName: "UpdateDeliveryOrder",
			Handler:    _ShippingService_UpdateDeliveryOrder_Handler,
		},
		{
			MethodName: "DeleteDeliveryOrder",
			Handler:    _ShippingService_DeleteDeliveryOrder_Handler,
		},
		{
			MethodName: "GeoCodeDeliveryOrder",
			Handler:    _ShippingService_GeoCodeDeliveryOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dms/v1/dms.proto",
}

// DeliveryOrderQueryServiceClient is the client API for DeliveryOrderQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeliveryOrderQueryServiceClient interface {
	ListDeliveryOrders(ctx context.Context, in *ListDeliveryOrdersRequest, opts ...grpc.CallOption) (*ListDeliveryOrdersResponse, error)
}

type deliveryOrderQueryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeliveryOrderQueryServiceClient(cc *grpc.ClientConn) DeliveryOrderQueryServiceClient {
	return &deliveryOrderQueryServiceClient{cc}
}

func (c *deliveryOrderQueryServiceClient) ListDeliveryOrders(ctx context.Context, in *ListDeliveryOrdersRequest, opts ...grpc.CallOption) (*ListDeliveryOrdersResponse, error) {
	out := new(ListDeliveryOrdersResponse)
	err := c.cc.Invoke(ctx, "/oswee.dms.v1.DeliveryOrderQueryService/ListDeliveryOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryOrderQueryServiceServer is the server API for DeliveryOrderQueryService service.
type DeliveryOrderQueryServiceServer interface {
	ListDeliveryOrders(context.Context, *ListDeliveryOrdersRequest) (*ListDeliveryOrdersResponse, error)
}

func RegisterDeliveryOrderQueryServiceServer(s *grpc.Server, srv DeliveryOrderQueryServiceServer) {
	s.RegisterService(&_DeliveryOrderQueryService_serviceDesc, srv)
}

func _DeliveryOrderQueryService_ListDeliveryOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeliveryOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryOrderQueryServiceServer).ListDeliveryOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.dms.v1.DeliveryOrderQueryService/ListDeliveryOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryOrderQueryServiceServer).ListDeliveryOrders(ctx, req.(*ListDeliveryOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeliveryOrderQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.dms.v1.DeliveryOrderQueryService",
	HandlerType: (*DeliveryOrderQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDeliveryOrders",
			Handler:    _DeliveryOrderQueryService_ListDeliveryOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dms/v1/dms.proto",
}
