// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dms/v1/dms.proto

package v1 // import "github.com/oswee/stubs/dms/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/oswee/stubs"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateDeliveryOrderRequest struct {
	DeliveryOrder        *DeliveryOrder `protobuf:"bytes,1,opt,name=delivery_order,json=deliveryOrder,proto3" json:"delivery_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateDeliveryOrderRequest) Reset()         { *m = CreateDeliveryOrderRequest{} }
func (m *CreateDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeliveryOrderRequest) ProtoMessage()    {}
func (*CreateDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dms_ef2b5b885cc630f5, []int{0}
}
func (m *CreateDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *CreateDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeliveryOrderRequest.Merge(dst, src)
}
func (m *CreateDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeliveryOrderRequest.Size(m)
}
func (m *CreateDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeliveryOrderRequest proto.InternalMessageInfo

func (m *CreateDeliveryOrderRequest) GetDeliveryOrder() *DeliveryOrder {
	if m != nil {
		return m.DeliveryOrder
	}
	return nil
}

type ListDeliveryOrdersRequest struct {
	StakeholderId        int64    `protobuf:"varint,1,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDeliveryOrdersRequest) Reset()         { *m = ListDeliveryOrdersRequest{} }
func (m *ListDeliveryOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryOrdersRequest) ProtoMessage()    {}
func (*ListDeliveryOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dms_ef2b5b885cc630f5, []int{1}
}
func (m *ListDeliveryOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Unmarshal(m, b)
}
func (m *ListDeliveryOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Marshal(b, m, deterministic)
}
func (dst *ListDeliveryOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryOrdersRequest.Merge(dst, src)
}
func (m *ListDeliveryOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryOrdersRequest.Size(m)
}
func (m *ListDeliveryOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryOrdersRequest proto.InternalMessageInfo

func (m *ListDeliveryOrdersRequest) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *ListDeliveryOrdersRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *ListDeliveryOrdersRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type ListDeliveryOrdersResponse struct {
	DeliveryOrders       []*DeliveryOrder `protobuf:"bytes,1,rep,name=delivery_orders,json=deliveryOrders,proto3" json:"delivery_orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListDeliveryOrdersResponse) Reset()         { *m = ListDeliveryOrdersResponse{} }
func (m *ListDeliveryOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*ListDeliveryOrdersResponse) ProtoMessage()    {}
func (*ListDeliveryOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dms_ef2b5b885cc630f5, []int{2}
}
func (m *ListDeliveryOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Unmarshal(m, b)
}
func (m *ListDeliveryOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Marshal(b, m, deterministic)
}
func (dst *ListDeliveryOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeliveryOrdersResponse.Merge(dst, src)
}
func (m *ListDeliveryOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_ListDeliveryOrdersResponse.Size(m)
}
func (m *ListDeliveryOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeliveryOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeliveryOrdersResponse proto.InternalMessageInfo

func (m *ListDeliveryOrdersResponse) GetDeliveryOrders() []*DeliveryOrder {
	if m != nil {
		return m.DeliveryOrders
	}
	return nil
}

type UpdateDeliveryOrderRequest struct {
	DeliveryOrder        *DeliveryOrder `protobuf:"bytes,1,opt,name=delivery_order,json=deliveryOrder,proto3" json:"delivery_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateDeliveryOrderRequest) Reset()         { *m = UpdateDeliveryOrderRequest{} }
func (m *UpdateDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeliveryOrderRequest) ProtoMessage()    {}
func (*UpdateDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dms_ef2b5b885cc630f5, []int{3}
}
func (m *UpdateDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *UpdateDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeliveryOrderRequest.Merge(dst, src)
}
func (m *UpdateDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeliveryOrderRequest.Size(m)
}
func (m *UpdateDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeliveryOrderRequest proto.InternalMessageInfo

func (m *UpdateDeliveryOrderRequest) GetDeliveryOrder() *DeliveryOrder {
	if m != nil {
		return m.DeliveryOrder
	}
	return nil
}

type DeleteDeliveryOrderRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeliveryOrderRequest) Reset()         { *m = DeleteDeliveryOrderRequest{} }
func (m *DeleteDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeliveryOrderRequest) ProtoMessage()    {}
func (*DeleteDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dms_ef2b5b885cc630f5, []int{4}
}
func (m *DeleteDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *DeleteDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeliveryOrderRequest.Merge(dst, src)
}
func (m *DeleteDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeliveryOrderRequest.Size(m)
}
func (m *DeleteDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeliveryOrderRequest proto.InternalMessageInfo

func (m *DeleteDeliveryOrderRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GeoCodeDeliveryOrderRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StakeholderId        int64    `protobuf:"varint,2,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoCodeDeliveryOrderRequest) Reset()         { *m = GeoCodeDeliveryOrderRequest{} }
func (m *GeoCodeDeliveryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GeoCodeDeliveryOrderRequest) ProtoMessage()    {}
func (*GeoCodeDeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dms_ef2b5b885cc630f5, []int{5}
}
func (m *GeoCodeDeliveryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoCodeDeliveryOrderRequest.Unmarshal(m, b)
}
func (m *GeoCodeDeliveryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoCodeDeliveryOrderRequest.Marshal(b, m, deterministic)
}
func (dst *GeoCodeDeliveryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoCodeDeliveryOrderRequest.Merge(dst, src)
}
func (m *GeoCodeDeliveryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GeoCodeDeliveryOrderRequest.Size(m)
}
func (m *GeoCodeDeliveryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoCodeDeliveryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeoCodeDeliveryOrderRequest proto.InternalMessageInfo

func (m *GeoCodeDeliveryOrderRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GeoCodeDeliveryOrderRequest) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *GeoCodeDeliveryOrderRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeliveryOrder struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StakeholderId        int64    `protobuf:"varint,2,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	Reference            string   `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	DestinationAddress   string   `protobuf:"bytes,4,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	DestinationZip       string   `protobuf:"bytes,5,opt,name=destination_zip,json=destinationZip,proto3" json:"destination_zip,omitempty"`
	DestinationLat       float64  `protobuf:"fixed64,6,opt,name=destination_lat,json=destinationLat,proto3" json:"destination_lat,omitempty"`
	DestinationLng       float64  `protobuf:"fixed64,7,opt,name=destination_lng,json=destinationLng,proto3" json:"destination_lng,omitempty"`
	TotalWeight          float64  `protobuf:"fixed64,8,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	RoutingSequence      int64    `protobuf:"varint,9,opt,name=routing_sequence,json=routingSequence,proto3" json:"routing_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveryOrder) Reset()         { *m = DeliveryOrder{} }
func (m *DeliveryOrder) String() string { return proto.CompactTextString(m) }
func (*DeliveryOrder) ProtoMessage()    {}
func (*DeliveryOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_dms_ef2b5b885cc630f5, []int{6}
}
func (m *DeliveryOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryOrder.Unmarshal(m, b)
}
func (m *DeliveryOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryOrder.Marshal(b, m, deterministic)
}
func (dst *DeliveryOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryOrder.Merge(dst, src)
}
func (m *DeliveryOrder) XXX_Size() int {
	return xxx_messageInfo_DeliveryOrder.Size(m)
}
func (m *DeliveryOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryOrder proto.InternalMessageInfo

func (m *DeliveryOrder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeliveryOrder) GetStakeholderId() int64 {
	if m != nil {
		return m.StakeholderId
	}
	return 0
}

func (m *DeliveryOrder) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationZip() string {
	if m != nil {
		return m.DestinationZip
	}
	return ""
}

func (m *DeliveryOrder) GetDestinationLat() float64 {
	if m != nil {
		return m.DestinationLat
	}
	return 0
}

func (m *DeliveryOrder) GetDestinationLng() float64 {
	if m != nil {
		return m.DestinationLng
	}
	return 0
}

func (m *DeliveryOrder) GetTotalWeight() float64 {
	if m != nil {
		return m.TotalWeight
	}
	return 0
}

func (m *DeliveryOrder) GetRoutingSequence() int64 {
	if m != nil {
		return m.RoutingSequence
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateDeliveryOrderRequest)(nil), "oswee.dms.v1.CreateDeliveryOrderRequest")
	proto.RegisterType((*ListDeliveryOrdersRequest)(nil), "oswee.dms.v1.ListDeliveryOrdersRequest")
	proto.RegisterType((*ListDeliveryOrdersResponse)(nil), "oswee.dms.v1.ListDeliveryOrdersResponse")
	proto.RegisterType((*UpdateDeliveryOrderRequest)(nil), "oswee.dms.v1.UpdateDeliveryOrderRequest")
	proto.RegisterType((*DeleteDeliveryOrderRequest)(nil), "oswee.dms.v1.DeleteDeliveryOrderRequest")
	proto.RegisterType((*GeoCodeDeliveryOrderRequest)(nil), "oswee.dms.v1.GeoCodeDeliveryOrderRequest")
	proto.RegisterType((*DeliveryOrder)(nil), "oswee.dms.v1.DeliveryOrder")
}

func init() { proto.RegisterFile("dms/v1/dms.proto", fileDescriptor_dms_ef2b5b885cc630f5) }

var fileDescriptor_dms_ef2b5b885cc630f5 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x7f, 0x6b, 0xd3, 0x40,
	0x18, 0x26, 0xad, 0xdb, 0xec, 0xdb, 0x35, 0x1d, 0x57, 0x85, 0x98, 0x29, 0xab, 0x05, 0x5d, 0x07,
	0xd2, 0xb0, 0xf9, 0x09, 0xdc, 0x2a, 0x22, 0x0c, 0x1d, 0x1d, 0x2a, 0x0c, 0x31, 0x26, 0xbd, 0x77,
	0xe9, 0x61, 0x9a, 0x3b, 0xef, 0x2e, 0x1d, 0xf3, 0x2b, 0xf8, 0x1d, 0xfd, 0x08, 0x7e, 0x06, 0xc9,
	0x35, 0xdd, 0x9a, 0x36, 0xed, 0x44, 0xf0, 0xcf, 0x3c, 0xef, 0x93, 0xe7, 0xfd, 0x75, 0xcf, 0x0b,
	0x3b, 0x74, 0xac, 0xbc, 0xc9, 0xa1, 0x47, 0xc7, 0xaa, 0x27, 0x24, 0xd7, 0x9c, 0x6c, 0x73, 0x75,
	0x85, 0xd8, 0xcb, 0x80, 0xc9, 0xa1, 0x6b, 0x1b, 0x30, 0x4c, 0x2f, 0xa7, 0xd1, 0xce, 0x57, 0x70,
	0x4f, 0x24, 0x06, 0x1a, 0xfb, 0x18, 0xb3, 0x09, 0xca, 0xeb, 0xf7, 0x92, 0xa2, 0x1c, 0xe0, 0xf7,
	0x14, 0x95, 0x26, 0xc7, 0x60, 0xd3, 0x1c, 0xf7, 0x79, 0x16, 0x70, 0xac, 0xb6, 0xd5, 0xad, 0x1f,
	0xed, 0xf6, 0xe6, 0x45, 0x7b, 0xc5, 0x7f, 0x1b, 0x74, 0xfe, 0xb3, 0xf3, 0xd3, 0x82, 0x47, 0xa7,
	0x4c, 0xe9, 0x02, 0x49, 0xcd, 0x32, 0x3c, 0x03, 0x5b, 0xe9, 0xe0, 0x1b, 0x8e, 0x78, 0x4c, 0x51,
	0xfa, 0x8c, 0x9a, 0x0c, 0xd5, 0x41, 0x63, 0x0e, 0x7d, 0x4b, 0xc9, 0x1e, 0xd4, 0x45, 0x10, 0xa1,
	0x9f, 0xa4, 0xe3, 0x10, 0xa5, 0x53, 0x69, 0x5b, 0xdd, 0x8d, 0x01, 0x64, 0xd0, 0x3b, 0x83, 0x90,
	0xe7, 0xd0, 0x94, 0xa8, 0xd2, 0x58, 0xfb, 0x02, 0xa5, 0x9f, 0x05, 0x9c, 0xaa, 0x21, 0x35, 0xa6,
	0xf0, 0x19, 0xca, 0xb3, 0x20, 0xc2, 0x4e, 0x08, 0x6e, 0x59, 0x31, 0x4a, 0xf0, 0x44, 0x21, 0xe9,
	0x43, 0xb3, 0xd8, 0xaf, 0x72, 0xac, 0x76, 0xf5, 0xae, 0x86, 0xed, 0x42, 0xc3, 0x2a, 0x9b, 0xe9,
	0x07, 0x41, 0xff, 0xe7, 0x4c, 0x5f, 0x80, 0xdb, 0xc7, 0x18, 0x57, 0x64, 0xb0, 0xa1, 0x72, 0x33,
	0xc7, 0x0a, 0xa3, 0x9d, 0x04, 0x76, 0xdf, 0x20, 0x3f, 0xe1, 0xf4, 0xaf, 0xe8, 0x25, 0x2b, 0xa9,
	0x94, 0xad, 0xc4, 0x81, 0xad, 0x80, 0x52, 0x89, 0x4a, 0x99, 0x49, 0xd7, 0x06, 0xb3, 0xcf, 0xce,
	0xaf, 0x0a, 0x34, 0x0a, 0x99, 0xfe, 0x35, 0xc5, 0x63, 0xa8, 0x49, 0xbc, 0x44, 0x89, 0xc9, 0x10,
	0xf3, 0x24, 0xb7, 0x00, 0xf1, 0xa0, 0x45, 0x51, 0x69, 0x96, 0x04, 0x9a, 0xf1, 0xc4, 0x9f, 0x15,
	0x73, 0xcf, 0xf0, 0xc8, 0x5c, 0xe8, 0xd5, 0x34, 0x42, 0xf6, 0xb3, 0xed, 0xde, 0xfe, 0xf0, 0x83,
	0x09, 0x67, 0xc3, 0x90, 0xed, 0x39, 0xf8, 0x82, 0x89, 0x45, 0x62, 0x1c, 0x68, 0x67, 0xb3, 0x6d,
	0x75, 0xad, 0x02, 0xf1, 0x34, 0xd0, 0x4b, 0xc4, 0x24, 0x72, 0xb6, 0x96, 0x89, 0x49, 0x44, 0x9e,
	0xc2, 0xb6, 0xe6, 0x3a, 0x88, 0xfd, 0x2b, 0x64, 0xd1, 0x48, 0x3b, 0xf7, 0x0d, 0xab, 0x6e, 0xb0,
	0x4f, 0x06, 0x22, 0x07, 0xb0, 0x23, 0x79, 0xaa, 0x59, 0x12, 0xf9, 0x2a, 0xdb, 0x4c, 0xd6, 0x73,
	0xcd, 0x4c, 0xa5, 0x99, 0xe3, 0xe7, 0x39, 0x7c, 0xf4, 0xbb, 0x0a, 0xcd, 0xf3, 0x11, 0x13, 0xc2,
	0x80, 0x72, 0xc2, 0x86, 0x48, 0x22, 0x20, 0xcb, 0x0f, 0x9b, 0xec, 0x17, 0x1f, 0xd5, 0x4a, 0x1f,
	0xba, 0xdd, 0xbb, 0x89, 0xb9, 0x47, 0x3e, 0x43, 0xab, 0xe4, 0x62, 0x90, 0x05, 0x81, 0xd5, 0x47,
	0xc5, 0x5d, 0xf7, 0xd0, 0x33, 0xf5, 0x12, 0xef, 0x2c, 0xaa, 0xaf, 0xb6, 0xd7, 0x7a, 0xf5, 0x8f,
	0xd0, 0x2a, 0xf1, 0xcd, 0xa2, 0xfa, 0x6a, 0x6b, 0xb9, 0x0f, 0x73, 0xe6, 0xcd, 0x15, 0x7d, 0x3d,
	0x16, 0xfa, 0x9a, 0x7c, 0x81, 0x07, 0x65, 0x0e, 0x23, 0x07, 0x45, 0xe1, 0x35, 0x2e, 0x5c, 0x5b,
	0xf7, 0xf1, 0xde, 0xc5, 0x93, 0x88, 0xe9, 0x51, 0x1a, 0xf6, 0x86, 0x7c, 0xec, 0x19, 0xa2, 0xa7,
	0x74, 0x1a, 0x2a, 0x6f, 0x7a, 0xee, 0xc3, 0x4d, 0x53, 0xd0, 0xcb, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x3b, 0x93, 0x5f, 0x47, 0xff, 0x05, 0x00, 0x00,
}
