// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/crm/crm.proto

package crm // import "github.com/oswee/pb/crm"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/oswee/pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCustomersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomersRequest) Reset()         { *m = GetCustomersRequest{} }
func (m *GetCustomersRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomersRequest) ProtoMessage()    {}
func (*GetCustomersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_crm_f1f9e6b48c11a89e, []int{0}
}
func (m *GetCustomersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomersRequest.Unmarshal(m, b)
}
func (m *GetCustomersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomersRequest.Marshal(b, m, deterministic)
}
func (dst *GetCustomersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomersRequest.Merge(dst, src)
}
func (m *GetCustomersRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomersRequest.Size(m)
}
func (m *GetCustomersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomersRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetCustomersRequest)(nil), "oswee.crm.v1.GetCustomersRequest")
}

func init() { proto.RegisterFile("v1/crm/crm.proto", fileDescriptor_crm_f1f9e6b48c11a89e) }

var fileDescriptor_crm_f1f9e6b48c11a89e = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x33, 0xd4, 0x4f,
	0x2e, 0xca, 0x05, 0x61, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x9e, 0xfc, 0xe2, 0xf2, 0xd4,
	0x54, 0x3d, 0x90, 0x40, 0x99, 0xa1, 0x94, 0x60, 0x99, 0xa1, 0x3e, 0x58, 0x3c, 0xa9, 0x34, 0x0d,
	0xa2, 0x40, 0x49, 0x94, 0x4b, 0xd8, 0x3d, 0xb5, 0xc4, 0xb9, 0xb4, 0xb8, 0x24, 0x3f, 0x37, 0xb5,
	0xa8, 0x38, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0xc4, 0x28, 0x88, 0x8b, 0xd9, 0xb9, 0x28, 0x57,
	0xc8, 0x9b, 0x8b, 0x07, 0x59, 0x56, 0x48, 0x51, 0x0f, 0xd9, 0x3c, 0x3d, 0x2c, 0x3a, 0xa5, 0x24,
	0xa0, 0x4a, 0xe0, 0xf6, 0x94, 0x19, 0xea, 0xb9, 0xe6, 0x16, 0x94, 0x54, 0x3a, 0x49, 0x46, 0x89,
	0xa7, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x83, 0x55, 0xe9, 0x17, 0x24,
	0x81, 0x1c, 0x9b, 0xc4, 0x06, 0x56, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xba, 0x1f,
	0x23, 0xc1, 0x00, 0x00, 0x00,
}
