// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signin/v1/signin.proto

package v1 // import "github.com/oswee/stubs/signin/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import stubs "github.com/oswee/stubs"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Credentials struct {
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_signin_93cc2afaac18ec18, []int{0}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Credentials)(nil), "oswee.signin.v1.Credentials")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SigninServiceClient is the client API for SigninService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SigninServiceClient interface {
	Signin(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*stubs.Empty, error)
}

type signinServiceClient struct {
	cc *grpc.ClientConn
}

func NewSigninServiceClient(cc *grpc.ClientConn) SigninServiceClient {
	return &signinServiceClient{cc}
}

func (c *signinServiceClient) Signin(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*stubs.Empty, error) {
	out := new(stubs.Empty)
	err := c.cc.Invoke(ctx, "/oswee.signin.v1.SigninService/Signin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigninServiceServer is the server API for SigninService service.
type SigninServiceServer interface {
	Signin(context.Context, *Credentials) (*stubs.Empty, error)
}

func RegisterSigninServiceServer(s *grpc.Server, srv SigninServiceServer) {
	s.RegisterService(&_SigninService_serviceDesc, srv)
}

func _SigninService_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigninServiceServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oswee.signin.v1.SigninService/Signin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigninServiceServer).Signin(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

var _SigninService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oswee.signin.v1.SigninService",
	HandlerType: (*SigninServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signin",
			Handler:    _SigninService_Signin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signin/v1/signin.proto",
}

func init() { proto.RegisterFile("signin/v1/signin.proto", fileDescriptor_signin_93cc2afaac18ec18) }

var fileDescriptor_signin_93cc2afaac18ec18 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xce, 0x4c, 0xcf,
	0xcb, 0xcc, 0xd3, 0x2f, 0x33, 0xd4, 0x87, 0xb0, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xf8,
	0xf3, 0x8b, 0xcb, 0x53, 0x53, 0xf5, 0xa0, 0x62, 0x65, 0x86, 0x52, 0x7c, 0x60, 0xf1, 0xa4, 0xd2,
	0x34, 0x88, 0x02, 0x25, 0x57, 0x2e, 0x6e, 0xe7, 0xa2, 0xd4, 0x94, 0xd4, 0xbc, 0x92, 0xcc, 0xc4,
	0x9c, 0x62, 0x21, 0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0xd4, 0xa2, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x1f, 0x24, 0x57, 0x90, 0x58, 0x5c, 0x5c, 0x9e, 0x5f, 0x94,
	0x22, 0xc1, 0x0c, 0x91, 0x83, 0xf1, 0x8d, 0xfc, 0xb8, 0x78, 0x83, 0xc1, 0x76, 0x04, 0xa7, 0x16,
	0x95, 0x65, 0x26, 0xa7, 0x0a, 0xd9, 0x72, 0xb1, 0x41, 0x04, 0x84, 0x64, 0xf4, 0xd0, 0xdc, 0xa0,
	0x87, 0x64, 0xa1, 0x94, 0x28, 0x54, 0x16, 0xee, 0x2c, 0xd7, 0xdc, 0x82, 0x92, 0x4a, 0x27, 0xa5,
	0x28, 0x85, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0xb0, 0x12, 0xfd,
	0xe2, 0x92, 0xd2, 0xa4, 0x62, 0x7d, 0xb8, 0x47, 0x93, 0xd8, 0xc0, 0x7a, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x28, 0xac, 0x67, 0xfc, 0x00, 0x00, 0x00,
}
